# Generated by Django 5.1.2 on 2024-10-29 18:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine_list', '0002_rename_descrtiption_manufacturer_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicinelist',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicinelist',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
